# needed for the 10 inch monitor
# xrandr --dpi 222
# xrandr --dpi 222

xset +fp /usr/local/share/fonts
xset fp rehash

xrdb -load .Xresources

xset s on
xset s blank
xset s 180
xset +dpms
xset dpms 240 300 300


xinput --set-prop 9 "libinput Accel Speed" -0.7

urxvt &

i3
